[2024-05-31T21:12:18.031+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T21:00:00+00:00 [queued]>
[2024-05-31T21:12:18.041+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T21:00:00+00:00 [queued]>
[2024-05-31T21:12:18.043+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-31T21:12:18.061+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 21:00:00+00:00
[2024-05-31T21:12:18.067+0000] {standard_task_runner.py:60} INFO - Started process 41809 to run task
[2024-05-31T21:12:18.070+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'scheduled__2024-05-31T21:00:00+00:00', '--job-id', '657', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmp81gc6n19']
[2024-05-31T21:12:18.072+0000] {standard_task_runner.py:88} INFO - Job 657: Subtask load_data_to_redshift
[2024-05-31T21:12:18.126+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T21:00:00+00:00 [running]> on host a71bb5ce980f
[2024-05-31T21:12:18.223+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-31T21:00:00+00:00'
[2024-05-31T21:12:18.277+0000] {logging_mixin.py:188} INFO -    Unnamed: 0      id  ... eventMetadata aggregatedEventPoints
0           0  816780  ...           NaN                   NaN
1           1  816776  ...           NaN                   NaN
2           2  818880  ...           NaN                   NaN
3           3  819319  ...           NaN                   NaN
4           4  819322  ...           NaN                   NaN

[5 rows x 24 columns]
[2024-05-31T21:12:18.285+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 48, in load_data_to_redshift
    df = get_participants(df)
  File "/opt/airflow/dags/tipico_transform.py", line 15, in get_participants
    list_in_cell = json.loads(row["participants"])
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 2218 (char 2217)
[2024-05-31T21:12:18.323+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T210000, start_date=20240531T211218, end_date=20240531T211218
[2024-05-31T21:12:18.346+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 657 for task load_data_to_redshift (Expecting ',' delimiter: line 1 column 2218 (char 2217); 41809)
[2024-05-31T21:12:18.366+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T21:12:18.395+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
