[2024-05-31T17:15:07.501+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T17:00:00+00:00 [queued]>
[2024-05-31T17:15:07.511+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T17:00:00+00:00 [queued]>
[2024-05-31T17:15:07.512+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-05-31T17:15:07.529+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 17:00:00+00:00
[2024-05-31T17:15:07.537+0000] {standard_task_runner.py:60} INFO - Started process 37971 to run task
[2024-05-31T17:15:07.540+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'scheduled__2024-05-31T17:00:00+00:00', '--job-id', '554', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmp5lxuck7x']
[2024-05-31T17:15:07.542+0000] {standard_task_runner.py:88} INFO - Job 554: Subtask load_data_to_redshift
[2024-05-31T17:15:07.600+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T17:00:00+00:00 [running]> on host a71bb5ce980f
[2024-05-31T17:15:07.691+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-31T17:00:00+00:00'
[2024-05-31T17:15:07.730+0000] {logging_mixin.py:188} INFO -    Unnamed: 0  ...  eventMetadata
0           0  ...            NaN
1           1  ...            NaN

[2 rows x 22 columns]
[2024-05-31T17:15:07.746+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T17:15:07.747+0000] {logging_mixin.py:188} INFO - {'id': 71233, 'name': 'Kato M / Kichenok N', 'position': 'HOME', 'abbreviation': 'KKI'} ---------------- 0
[2024-05-31T17:15:07.748+0000] {logging_mixin.py:188} INFO - {'id': 39274, 'name': 'Saville D / Tomljanovic A', 'position': 'AWAY', 'abbreviation': 'STO'} ---------------- 0
[2024-05-31T17:15:07.749+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T17:15:07.750+0000] {logging_mixin.py:188} INFO - {'id': 86144, 'name': 'Jacquemot E / Tan H', 'position': 'HOME', 'abbreviation': 'JTA'} ---------------- 1
[2024-05-31T17:15:07.751+0000] {logging_mixin.py:188} INFO - {'id': 30924, 'name': 'Mihalikova T / Noskova L', 'position': 'AWAY', 'abbreviation': 'MNO'} ---------------- 1
[2024-05-31T17:15:07.819+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 188, in load_data_to_redshift
    df = get_markets(df)
  File "/opt/airflow/dags/tipico_etl.py", line 127, in get_markets
    df.to_csv('./data/test_markets_merged.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: './data/test_markets_merged.csv'
[2024-05-31T17:15:07.836+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T170000, start_date=20240531T171507, end_date=20240531T171507
[2024-05-31T17:15:07.849+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 554 for task load_data_to_redshift ([Errno 13] Permission denied: './data/test_markets_merged.csv'; 37971)
[2024-05-31T17:15:07.875+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T17:15:07.891+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
