[2024-05-31T10:10:04.199+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T10:00:00+00:00 [queued]>
[2024-05-31T10:10:04.208+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T10:00:00+00:00 [queued]>
[2024-05-31T10:10:04.209+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-31T10:10:04.224+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 10:00:00+00:00
[2024-05-31T10:10:04.230+0000] {standard_task_runner.py:60} INFO - Started process 31919 to run task
[2024-05-31T10:10:04.233+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'scheduled__2024-05-31T10:00:00+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmpm_8trrtd']
[2024-05-31T10:10:04.235+0000] {standard_task_runner.py:88} INFO - Job 347: Subtask load_data_to_redshift
[2024-05-31T10:10:04.283+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T10:00:00+00:00 [running]> on host a71bb5ce980f
[2024-05-31T10:10:04.360+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-31T10:00:00+00:00'
[2024-05-31T10:10:04.405+0000] {logging_mixin.py:188} INFO -    Unnamed: 0  ...                           eventMetadata
0           0  ...                                     NaN
1           1  ...                                     NaN
2           2  ...                                     NaN
3           3  ...                                     NaN
4           4  ...  {'event-widget': {'providerId': '71'}}

[5 rows x 23 columns]
[2024-05-31T10:10:04.409+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 64, in load_data_to_redshift
    df = get_participants(df)
  File "/opt/airflow/dags/tipico_etl.py", line 17, in get_participants
    dictionary['match_id'] = df['id'][index]
TypeError: 'str' object does not support item assignment
[2024-05-31T10:10:04.425+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T100000, start_date=20240531T101004, end_date=20240531T101004
[2024-05-31T10:10:04.436+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 347 for task load_data_to_redshift ('str' object does not support item assignment; 31919)
[2024-05-31T10:10:04.448+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T10:10:04.463+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
