[2024-05-31T12:30:38.365+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T12:25:30.977167+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
