[2024-05-31T16:50:04.705+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T16:40:00+00:00 [queued]>
[2024-05-31T16:50:04.713+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T16:40:00+00:00 [queued]>
[2024-05-31T16:50:04.714+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-31T16:50:04.727+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 16:40:00+00:00
[2024-05-31T16:50:04.734+0000] {standard_task_runner.py:60} INFO - Started process 37577 to run task
[2024-05-31T16:50:04.737+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'scheduled__2024-05-31T16:40:00+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmp_5ppgw0q']
[2024-05-31T16:50:04.739+0000] {standard_task_runner.py:88} INFO - Job 547: Subtask load_data_to_redshift
[2024-05-31T16:50:04.794+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T16:40:00+00:00 [running]> on host a71bb5ce980f
[2024-05-31T16:50:04.879+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T16:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-31T16:40:00+00:00'
[2024-05-31T16:50:04.919+0000] {logging_mixin.py:188} INFO -    Unnamed: 0  ...  eventMetadata
0           0  ...            NaN
1           1  ...            NaN

[2 rows x 22 columns]
[2024-05-31T16:50:04.931+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T16:50:04.932+0000] {logging_mixin.py:188} INFO - {'id': 71233, 'name': 'Kato M / Kichenok N', 'position': 'HOME', 'abbreviation': 'KKI'} ---------------- 0
[2024-05-31T16:50:04.932+0000] {logging_mixin.py:188} INFO - {'id': 39274, 'name': 'Saville D / Tomljanovic A', 'position': 'AWAY', 'abbreviation': 'STO'} ---------------- 0
[2024-05-31T16:50:04.933+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T16:50:04.934+0000] {logging_mixin.py:188} INFO - {'id': 86144, 'name': 'Jacquemot E / Tan H', 'position': 'HOME', 'abbreviation': 'JTA'} ---------------- 1
[2024-05-31T16:50:04.935+0000] {logging_mixin.py:188} INFO - {'id': 30924, 'name': 'Mihalikova T / Noskova L', 'position': 'AWAY', 'abbreviation': 'MNO'} ---------------- 1
[2024-05-31T16:50:05.051+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 191, in load_data_to_redshift
    df = get_market_outcome(df)
  File "/opt/airflow/dags/tipico_etl.py", line 142, in get_market_outcome
    markets_outcomes_flattened.to_csv('./data/test_markets_outcome_data.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: './data/test_markets_outcome_data.csv'
[2024-05-31T16:50:05.072+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T164000, start_date=20240531T165004, end_date=20240531T165005
[2024-05-31T16:50:05.088+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 547 for task load_data_to_redshift ([Errno 13] Permission denied: './data/test_markets_outcome_data.csv'; 37577)
[2024-05-31T16:50:05.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T16:50:05.134+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
