[2024-05-31T11:10:04.031+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T11:00:00+00:00 [queued]>
[2024-05-31T11:10:04.040+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T11:00:00+00:00 [queued]>
[2024-05-31T11:10:04.041+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-31T11:10:04.056+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 11:00:00+00:00
[2024-05-31T11:10:04.062+0000] {standard_task_runner.py:60} INFO - Started process 32903 to run task
[2024-05-31T11:10:04.066+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'scheduled__2024-05-31T11:00:00+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmp_fwy_3a7']
[2024-05-31T11:10:04.068+0000] {standard_task_runner.py:88} INFO - Job 379: Subtask load_data_to_redshift
[2024-05-31T11:10:04.119+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T11:00:00+00:00 [running]> on host a71bb5ce980f
[2024-05-31T11:10:04.206+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-31T11:00:00+00:00'
[2024-05-31T11:10:04.247+0000] {logging_mixin.py:188} INFO -    Unnamed: 0      id  ... eventMetadata aggregatedEventPoints
0           0  816775  ...           NaN                   NaN
1           1  814918  ...           NaN                   NaN
2           2  814933  ...           NaN                   NaN
3           3  814872  ...           NaN                   NaN
4           4  816776  ...           NaN                   NaN

[5 rows x 24 columns]
[2024-05-31T11:10:04.254+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 113, in load_data_to_redshift
    df = get_participants(df)
  File "/opt/airflow/dags/tipico_etl.py", line 16, in get_participants
    list_in_cell = json.loads(row["participants"])
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 13000 (char 12999)
[2024-05-31T11:10:04.263+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T110000, start_date=20240531T111004, end_date=20240531T111004
[2024-05-31T11:10:04.277+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 379 for task load_data_to_redshift (Expecting ',' delimiter: line 1 column 13000 (char 12999); 32903)
[2024-05-31T11:10:04.321+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T11:10:04.337+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
