[2024-05-31T02:53:39.469+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T02:53:33.567971+00:00 [queued]>
[2024-05-31T02:53:39.480+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T02:53:33.567971+00:00 [queued]>
[2024-05-31T02:53:39.481+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-31T02:53:39.501+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 02:53:33.567971+00:00
[2024-05-31T02:53:39.509+0000] {standard_task_runner.py:60} INFO - Started process 25240 to run task
[2024-05-31T02:53:39.513+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'manual__2024-05-31T02:53:33.567971+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmp1p6qavqu']
[2024-05-31T02:53:39.516+0000] {standard_task_runner.py:88} INFO - Job 258: Subtask load_data_to_redshift
[2024-05-31T02:53:39.579+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T02:53:33.567971+00:00 [running]> on host a71bb5ce980f
[2024-05-31T02:53:39.686+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T02:53:33.567971+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T02:53:33.567971+00:00'
[2024-05-31T02:53:39.742+0000] {logging_mixin.py:188} INFO -    Unnamed: 0  ...  eventMetadata
0           0  ...            NaN
1           1  ...            NaN
2           2  ...            NaN
3           3  ...            NaN
4           4  ...            NaN

[5 rows x 22 columns]
[2024-05-31T02:53:39.755+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2024-05-31T02:53:41.187+0000] {logging_mixin.py:188} INFO - {814989}
[2024-05-31T02:53:41.197+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 40, in load_data_to_redshift
    cursor.execute(sql, {row['id']}, {row['startTime']}, {row['messageTime']},{row['sportType']}, {row['matchState']},{row['participants']}, {row['status']},{row['marketCount']}, {row['group']},{row['markets']}, {row['eventType']},{row['updatesCount']}, {row['displayInfo']},{row['score']}, {row['gameClock']},{row['eventReferences']}, {row['eventDetails']},{row['sportCurrentGameState']}, {row['lastModifiedTime']},{row['eventTags']})
TypeError: execute() takes from 2 to 5 positional arguments but 22 were given
[2024-05-31T02:53:41.245+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T025333, start_date=20240531T025339, end_date=20240531T025341
[2024-05-31T02:53:41.272+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 258 for task load_data_to_redshift (execute() takes from 2 to 5 positional arguments but 22 were given; 25240)
[2024-05-31T02:53:41.297+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T02:53:41.466+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
