[2024-05-31T11:35:06.997+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T11:20:00+00:00 [queued]>
[2024-05-31T11:35:07.008+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T11:20:00+00:00 [queued]>
[2024-05-31T11:35:07.009+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-05-31T11:35:07.025+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 11:20:00+00:00
[2024-05-31T11:35:07.036+0000] {standard_task_runner.py:60} INFO - Started process 33311 to run task
[2024-05-31T11:35:07.040+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'scheduled__2024-05-31T11:20:00+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmpydz8o1w8']
[2024-05-31T11:35:07.042+0000] {standard_task_runner.py:88} INFO - Job 390: Subtask load_data_to_redshift
[2024-05-31T11:35:07.134+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-31T11:20:00+00:00 [running]> on host a71bb5ce980f
[2024-05-31T11:35:07.269+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T11:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-31T11:20:00+00:00'
[2024-05-31T11:35:07.328+0000] {logging_mixin.py:188} INFO -    Unnamed: 0  ...  eventMetadata
0           0  ...            NaN
1           1  ...            NaN

[2 rows x 22 columns]
[2024-05-31T11:35:07.345+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T11:35:07.347+0000] {logging_mixin.py:188} INFO - {'id': 71233, 'name': 'Kato M / Kichenok N', 'position': 'HOME', 'abbreviation': 'KKI'} ---------------- 0
[2024-05-31T11:35:07.349+0000] {logging_mixin.py:188} INFO - {'id': 39274, 'name': 'Saville D / Tomljanovic A', 'position': 'AWAY', 'abbreviation': 'STO'} ---------------- 0
[2024-05-31T11:35:07.350+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T11:35:07.351+0000] {logging_mixin.py:188} INFO - {'id': 86144, 'name': 'Jacquemot E / Tan H', 'position': 'HOME', 'abbreviation': 'JTA'} ---------------- 1
[2024-05-31T11:35:07.352+0000] {logging_mixin.py:188} INFO - {'id': 30924, 'name': 'Mihalikova T / Noskova L', 'position': 'AWAY', 'abbreviation': 'MNO'} ---------------- 1
[2024-05-31T11:35:07.384+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 118, in load_data_to_redshift
    df = get_eventDetails(df)
  File "/opt/airflow/dags/tipico_etl.py", line 40, in get_eventDetails
    eventDetails_df = eventDetails_df.drop_duplicates(subset=['match_id'], keep = 'last')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6522, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6654, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['match_id'], dtype='object')
[2024-05-31T11:35:07.410+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T112000, start_date=20240531T113507, end_date=20240531T113507
[2024-05-31T11:35:07.423+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 390 for task load_data_to_redshift (Index(['match_id'], dtype='object'); 33311)
[2024-05-31T11:35:07.456+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T11:35:07.476+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
