[2024-05-31T12:11:39.062+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T12:11:34.532161+00:00 [queued]>
[2024-05-31T12:11:39.082+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T12:11:34.532161+00:00 [queued]>
[2024-05-31T12:11:39.084+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-31T12:11:39.113+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 12:11:34.532161+00:00
[2024-05-31T12:11:39.128+0000] {standard_task_runner.py:60} INFO - Started process 33970 to run task
[2024-05-31T12:11:39.136+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'manual__2024-05-31T12:11:34.532161+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmpp8r44oku']
[2024-05-31T12:11:39.139+0000] {standard_task_runner.py:88} INFO - Job 428: Subtask load_data_to_redshift
[2024-05-31T12:11:39.249+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T12:11:34.532161+00:00 [running]> on host a71bb5ce980f
[2024-05-31T12:11:39.412+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T12:11:34.532161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T12:11:34.532161+00:00'
[2024-05-31T12:11:39.480+0000] {logging_mixin.py:188} INFO -    Unnamed: 0  ...  eventMetadata
0           0  ...            NaN
1           1  ...            NaN

[2 rows x 22 columns]
[2024-05-31T12:11:39.497+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T12:11:39.498+0000] {logging_mixin.py:188} INFO - {'id': 71233, 'name': 'Kato M / Kichenok N', 'position': 'HOME', 'abbreviation': 'KKI'} ---------------- 0
[2024-05-31T12:11:39.499+0000] {logging_mixin.py:188} INFO - {'id': 39274, 'name': 'Saville D / Tomljanovic A', 'position': 'AWAY', 'abbreviation': 'STO'} ---------------- 0
[2024-05-31T12:11:39.501+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T12:11:39.507+0000] {logging_mixin.py:188} INFO - {'id': 86144, 'name': 'Jacquemot E / Tan H', 'position': 'HOME', 'abbreviation': 'JTA'} ---------------- 1
[2024-05-31T12:11:39.508+0000] {logging_mixin.py:188} INFO - {'id': 30924, 'name': 'Mihalikova T / Noskova L', 'position': 'AWAY', 'abbreviation': 'MNO'} ---------------- 1
[2024-05-31T12:11:39.558+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 140, in load_data_to_redshift
    df = get_eventDetails(df, 'eventDetails')
  File "/opt/airflow/dags/tipico_etl.py", line 53, in get_eventDetails
    print('here is the ed dictionary----', ed_dict.type())
AttributeError: 'str' object has no attribute 'type'
[2024-05-31T12:11:39.585+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T121134, start_date=20240531T121139, end_date=20240531T121139
[2024-05-31T12:11:39.613+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 428 for task load_data_to_redshift ('str' object has no attribute 'type'; 33970)
[2024-05-31T12:11:39.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T12:11:39.692+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
