[2024-05-31T12:23:42.777+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T12:23:38.696705+00:00 [queued]>
[2024-05-31T12:23:42.793+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T12:23:38.696705+00:00 [queued]>
[2024-05-31T12:23:42.794+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-31T12:23:42.814+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-31 12:23:38.696705+00:00
[2024-05-31T12:23:42.822+0000] {standard_task_runner.py:60} INFO - Started process 34211 to run task
[2024-05-31T12:23:42.826+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'manual__2024-05-31T12:23:38.696705+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmpsusvxwi_']
[2024-05-31T12:23:42.828+0000] {standard_task_runner.py:88} INFO - Job 447: Subtask load_data_to_redshift
[2024-05-31T12:23:42.893+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-31T12:23:38.696705+00:00 [running]> on host a71bb5ce980f
[2024-05-31T12:23:42.984+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T12:23:38.696705+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T12:23:38.696705+00:00'
[2024-05-31T12:23:43.026+0000] {logging_mixin.py:188} INFO -    Unnamed: 0  ...  eventMetadata
0           0  ...            NaN
1           1  ...            NaN

[2 rows x 22 columns]
[2024-05-31T12:23:43.045+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T12:23:43.046+0000] {logging_mixin.py:188} INFO - {'id': 71233, 'name': 'Kato M / Kichenok N', 'position': 'HOME', 'abbreviation': 'KKI'} ---------------- 0
[2024-05-31T12:23:43.048+0000] {logging_mixin.py:188} INFO - {'id': 39274, 'name': 'Saville D / Tomljanovic A', 'position': 'AWAY', 'abbreviation': 'STO'} ---------------- 0
[2024-05-31T12:23:43.050+0000] {logging_mixin.py:188} INFO - 2
[2024-05-31T12:23:43.051+0000] {logging_mixin.py:188} INFO - {'id': 86144, 'name': 'Jacquemot E / Tan H', 'position': 'HOME', 'abbreviation': 'JTA'} ---------------- 1
[2024-05-31T12:23:43.052+0000] {logging_mixin.py:188} INFO - {'id': 30924, 'name': 'Mihalikova T / Noskova L', 'position': 'AWAY', 'abbreviation': 'MNO'} ---------------- 1
[2024-05-31T12:23:43.105+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 149, in load_data_to_redshift
    df = get_group(df, 'group', 'group')
  File "/opt/airflow/dags/tipico_etl.py", line 109, in get_group
    merged_df = df.merge(group_df, left_on='id', right_on='match_id').drop(columns=['match_id'])
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1203, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'match_id'
[2024-05-31T12:23:43.130+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240531T122338, start_date=20240531T122342, end_date=20240531T122343
[2024-05-31T12:23:43.145+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 447 for task load_data_to_redshift ('match_id'; 34211)
[2024-05-31T12:23:43.162+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T12:23:43.189+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
